baseurl = "https://blog.r-hub.io/"
languageCode = "en-us"
buildFuture = "true"
title = "R-hub blog"
theme = "hugo-lithium"
enableEmoji = true
pygmentsUseClasses=true
googleAnalytics = "UA-141769052-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "index\\.html", '\.knit\.md$', '\.utf8\.md$']
rssLimit = 5
removePathAccents = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 3 
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/r-hub"
    weight = 4
    pre = "<i class=\"fa fa-github\"></i>"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rhub_"
    weight = 5
    pre = "<i class=\"fa fa-twitter\"></i>"

[params]
    description = "Blog for the R-hub project of the R Consortium, easing the R package development process."
    customCSS = ["css/friendly.css", "css/rhub.css"]
    githubsource = "https://github.com/r-hub/blog/blob/master/content/"

    [params.logo]
    url = "images/logo.png"
    width = 50
    height = 50
    alt = "Logo"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"


[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
    
 [markup]
   [markup.goldmark]
     [markup.goldmark.renderer]
       unsafe = true
